//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FleetConnectAssessmentEntities : DbContext
    {
        public FleetConnectAssessmentEntities()
            : base("name=FleetConnectAssessmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeJob> EmployeeJobs { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<SECURITY_Permission> SECURITY_Permission { get; set; }
        public virtual DbSet<SECURITY_Role> SECURITY_Role { get; set; }
        public virtual DbSet<SECURITY_RolePermission> SECURITY_RolePermission { get; set; }
        public virtual DbSet<SECURITY_User> SECURITY_User { get; set; }
        public virtual DbSet<SECURITY_UserRole> SECURITY_UserRole { get; set; }
        public virtual DbSet<vw_AppliedJobs> vw_AppliedJobs { get; set; }
        public virtual DbSet<vw_EmployeeEmailFromJobApplication> vw_EmployeeEmailFromJobApplication { get; set; }
        public virtual DbSet<vw_Jobs> vw_Jobs { get; set; }
        public virtual DbSet<CompanyUser> CompanyUsers { get; set; }
    }
}
