//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AppliedJobs
    {
        public int JobID { get; set; }
        public string Title { get; set; }
        public string JobDescription { get; set; }
        public string Keywords { get; set; }
        public string Category { get; set; }
        public int CompanyID { get; set; }
        public int EmployeeJobID { get; set; }
        public int EmployeeID { get; set; }
        public byte[] Resume { get; set; }
        public System.DateTime DateLogged { get; set; }
        public string Name { get; set; }
        public int YearsOfExperience { get; set; }
        public string Status { get; set; }
    }
}
