//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmployeeEmailFromJobApplication
    {
        public int EmployeeJobID { get; set; }
        public int EmployeeID { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string JobTitle { get; set; }
        public string JobStatus { get; set; }
    }
}
